version: "3.9"
services:
  db:
    container_name: db-treinamento-educbank
    image: mongo:7.0.4
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  redis:
    container_name: redis-treinamento-educbank
    image: redis:alpine3.19
    ports:
      - 6379:6379

  rabbitmq:
    container_name: rabbitmq-treinamento-educbank
    image: rabbitmq:3-management-alpine
    expose:
      - 5672
      - 15672
    ports:
      - "15672:15672"
      - "5672:5672"

  minio:
    image: minio/minio
    container_name: educbank-infra-minio
    volumes:
      - minio_data:/export
      - minio_config:/root/.minio
    expose:
      - 9000
      - 9001
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    command: server /export --console-address ":9001"

volumes:
  db_data:
  minio_config:
  minio_data: